### ISSUE TITLE
Multiple domains/subdomains

### ISSUE THREAD

**Issue by cblevins** [da4asandbox/curricularsite#2]
We need to check to make sure it's. possible for a card to have multiple domains/subdomains.

**Comment by cblevins** [comment]
I *think* I have it figured out. I've merged my code edits to teh toolkit page. @Lore3581 can you do some testing and flag anything that might not be working as a comment on this issue?  It's a lot of very ugly nested for and if statements, but it seems to be working on my end. Otherwise if you think it's good you can close this issue.

**Comment by Lore3581** [comment]
@cblevins I tried adding all of the domains and subdomains to the test card double-check the filtering functionality and various combinations of domains and subdomains... in doing so, I somehow broke the filtering that was initially working. The formatting still shows up correctly (thank you so much for figuring that out!), but the filters no longer include the test card in any of the searches. I'm not sure what I did that might have broken it, especially as this was the commit to our test card that seemed to break the filtering: https://github.com/da4asandbox/curricularsite/commit/d2ba7629c446ae90e206698459e8509f7f7d8455

I experimented with having ChatGPT help me revise the Javascript, as I suspect that was likely the culprit. After a few attempts of revisions, I think I might have gotten it to work. Would you mind checking again to make sure everything is still showing up correctly on your end from a design standpoint and that the filtering is working as well? 

Additionally, the hyperlinks on the cards with only a single domain were also initially broken and redirected to the homepage: 
![Screenshot 2024-05-22 at 3 11 09 PM](https://github.com/da4asandbox/curricularsite/assets/113584473/532d1dc0-fea4-4f62-8fa9-44d27971c517)

I believe I was able to resolve this by adding:

https://github.com/da4asandbox/curricularsite/edit/master/_pages/toolkit.md#152

and 

https://github.com/da4asandbox/curricularsite/edit/master/_pages/toolkit.md#154

Would you mind also checking that all of the domain URLs are directing where they are supposed to on your end? 

If both of those revisions are showing up properly on your end, feel free to mark this as resolved!
